"""empty message

Revision ID: ed1a7888ff9b
Revises: 
Create Date: 2023-10-09 20:22:56.320678

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ed1a7888ff9b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('user_phoneno',
               existing_type=mysql.FLOAT(),
               type_=sa.String(length=45),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('user_phoneno',
               existing_type=sa.String(length=45),
               type_=mysql.FLOAT(),
               existing_nullable=False)

    # ### end Alembic commands ###
